package com.company.jobServer.beans;

import com.company.jobServer.common.orchestration.DeploymentType;
import com.company.jobServer.beans.enums.JobStatus;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;

/**
 * A JobExecution holds the information about one execution of a specific Job.
 */
@Data
@Entity
@Table(name = "job_executions")
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class JobExecution extends AbstractDatabaseItem {

  @ManyToOne()
  @JoinColumn(name = "job_id", insertable = false, updatable = false)
  @JsonIgnore
  private Job job;

  @Column(name = "job_id")
  @NotNull
  @ApiModelProperty(required = true, value = "Foreign key to Job")
  private Long jobId;

  @Column(name = "tenant_id")
  @ApiModelProperty(value = "Tenant Id")
  private String tenantId;

  @Column(name = "namespace")
  @ApiModelProperty(value = "Namespace")
  private String namespace;

  @Column(name = "deployment_type")
  @ApiModelProperty(value = "DeploymentType")
  private DeploymentType deploymentType;

  @Column(name = "input_parameters")
  @ApiModelProperty(value = "JSON string containing input parameters")
  private String inputParameters = null;

  @Column(name = "deployment_handle")
  @ApiModelProperty(value = "Deployment handle") // Contains name of handle
  private String deploymentHandle;

  @Column(name = "handle_data")
  @ApiModelProperty(value = "Auto generated by framework") // JSON serialized
  private String handleData;

  @Column(name = "status")
  @Enumerated(EnumType.STRING)
  @ApiModelProperty(value = "Status of the Job")
  private JobStatus status;

  @Column(name = "started_at")
  @ApiModelProperty(value = "Job start time")
  private Timestamp startedAt;

  @Column(name = "stopped_at")
  @ApiModelProperty(value = "Job end time")
  private Timestamp stoppedAt;

  @Column(name = "numReplicas")
  @ApiModelProperty(value = "Number of pod replicas running at any time. Cannot be specified if Autoscaler is enabled. Minimum value: 0")
  private Long numReplicas = null;

  @Column(name = "output_location")
  @ApiModelProperty(value = "OutputLocation for this execution")
  private String outputLocation;
}
