apiVersion: v1
kind: Pod
metadata:
  name: major-incident-job
  namespace: default
spec:
  containers:
  - args:
    - chmod +x run_training; ./run_training
    command:
    - /bin/bash
    - -c
    env:
    - name: aisera_pubsub_host_ports
      value: aisera-pubsub-kafka-0.aisera-pubsub-kafka-headless.default.svc.cluster.local:9092,aisera-pubsub-kafka-1.aisera-pubsub-kafka-headless.default.svc.cluster.local:9092,aisera-pubsub-kafka-2.aisera-pubsub-kafka-headless.default.svc.cluster.local:9092
    - name: aisera_io_python_pubsub_plugin
      value: redis
    - name: aisera_config
      value: '{"output-bucket":"aiseratenants-dev2","output-path":"10000/ModelStore/major-incident-model/temp","input-bucket":"aiseratenants-dev2","input-path":"10000/RawData/Incidents","tenant-id":"10000","recency-hour":"10000"}'
    - name: aisera_connector_config
      value: '{"output-bucket":"aiseratenants-dev2","output-path":"10000/ModelStore/major-incident-model/temp","input-bucket":"aiseratenants-dev2","input-path":"10000/RawData/Incidents","tenant-id":"10000","recency-hour":"10000"}'
    - name: aisera_training_input_config
      value: '{"output-bucket":"aiseratenants-dev2","output-path":"10000/ModelStore/major-incident-model/temp","input-bucket":"aiseratenants-dev2","input-path":"10000/RawData/Incidents","tenant-id":"10000","recency-hour":"10000"}'
    - name: aisera_deployment_handle
      value: major-incident-job-1530497394887-73
    - name: aisera_kv_redis_host
      value: redis
    - name: aisera_sql_user
      value: root
    - name: aisera_datastores_sql_host
      value: mariadb
    - name: aisera_datastores_sql_port
      value: "3306"
    - name: aisera_training_hyperparams
      value: '{}'
    - name: aisera_sql_password
      value: rootroot
    envFrom:
    - configMapRef:
        name: aisera-config
    - secretRef:
        name: aisera-secrets
    image: 934101271236.dkr.ecr.us-west-2.amazonaws.com/major-incident:Milestone_8.1
    imagePullPolicy: Always
    name: major-incident-job
  restartPolicy: Never